"""Generated segment modules for runtime-interception traces."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

import torch

from ariadne.trace.interception import (
    CapturedOp,
    InterceptionTraceArtifact,
    assign_template,
    materialize_template,
    resolve_template,
)


class GeneratedInterceptionSegment(torch.nn.Module):
    """A static generated segment over captured runtime ops.

    The module has no node-dispatch loop in ``forward`` generated by Python
    source. Each captured operation is emitted as a direct statement that calls
    ``_run_op`` for that specific op slot.
    """

    def __init__(
        self,
        *,
        root: torch.nn.Module,
        artifact: InterceptionTraceArtifact,
        ops: tuple[CapturedOp, ...],
        input_names: tuple[str, ...],
        output_template: Any,
        class_name: str,
    ) -> None:
        super().__init__()
        self.root = root
        self.artifact = artifact
        self.ops = ops
        self.input_names = input_names
        self.output_template = output_template
        self._parameters_by_name = dict(root.named_parameters())
        self._buffers_by_name = dict(root.named_buffers())
        source = _segment_source(len(ops), class_name)
        namespace: dict[str, Any] = {}
        exec(source, namespace)
        self._generated_forward = namespace["forward"].__get__(self, self.__class__)
        self.generated_source = source

    def forward(self, *inputs: Any) -> Any:
        return self._generated_forward(*inputs)

    def _new_env(self, inputs: tuple[Any, ...]) -> dict[str, Any]:
        if len(inputs) != len(self.input_names):
            raise ValueError(f"Expected {len(self.input_names)} inputs, got {len(inputs)}.")
        env = dict(zip(self.input_names, inputs, strict=True))
        for value in inputs:
            if isinstance(value, torch.Tensor) and value.ndim > 0:
                env["B"] = int(value.shape[0])
                break
        return env

    def _run_op(self, index: int, env: dict[str, Any]) -> None:
        op = self.ops[index]
        args = resolve_template(
            op.args_template,
            env=env,
            parameters=self._parameters_by_name,
            buffers=self._buffers_by_name,
            root=self.root,
        )
        kwargs = resolve_template(
            op.kwargs_template,
            env=env,
            parameters=self._parameters_by_name,
            buffers=self._buffers_by_name,
            root=self.root,
        )
        result = op.callable_ref(*args, **kwargs)
        assign_template(result, op.output_template, env)

    def _materialize_output(self, env: dict[str, Any]) -> Any:
        return materialize_template(self.output_template, env)


class InterpretedInterceptionSegment(torch.nn.Module):
    """Node-by-node execution over captured ops for debug mode only."""

    def __init__(self, generated: GeneratedInterceptionSegment) -> None:
        super().__init__()
        self.generated = generated

    def forward(self, *inputs: Any) -> Any:
        env = self.generated._new_env(inputs)
        for index in range(len(self.generated.ops)):
            self.generated._run_op(index, env)
        return self.generated._materialize_output(env)


def as_debug_interpreter(segment: torch.nn.Module) -> torch.nn.Module:
    if not isinstance(segment, GeneratedInterceptionSegment):
        raise TypeError("debug_interpreter requires a generated interception segment.")
    return InterpretedInterceptionSegment(segment)


def build_interception_prefix(
    *,
    root: torch.nn.Module,
    artifact: InterceptionTraceArtifact,
    op_names: Iterable[str],
    raw_input_names: tuple[str, ...],
    boundary_order: tuple[str, ...],
) -> GeneratedInterceptionSegment:
    selected_ops = _select_ops(artifact, op_names)
    return GeneratedInterceptionSegment(
        root=root,
        artifact=artifact,
        ops=selected_ops,
        input_names=raw_input_names,
        output_template=tuple(materialize_name(name) for name in boundary_order),
        class_name="PrefixSegment",
    )


def build_interception_suffix(
    *,
    root: torch.nn.Module,
    artifact: InterceptionTraceArtifact,
    op_names: Iterable[str],
    boundary_order: tuple[str, ...],
    passthrough_order: tuple[str, ...],
) -> GeneratedInterceptionSegment:
    selected_ops = _select_ops(artifact, op_names)
    return GeneratedInterceptionSegment(
        root=root,
        artifact=artifact,
        ops=selected_ops,
        input_names=(*boundary_order, *passthrough_order),
        output_template=artifact.output_template,
        class_name="SuffixSegment",
    )


def materialize_name(name: str) -> Any:
    from ariadne.trace.interception import NodeArg

    return NodeArg(name)


def _select_ops(
    artifact: InterceptionTraceArtifact,
    op_names: Iterable[str],
) -> tuple[CapturedOp, ...]:
    wanted = set(op_names)
    return tuple(op for op in artifact.ops if any(name in wanted for name in op.output_names))


def _segment_source(op_count: int, class_name: str) -> str:
    lines = [
        "def forward(self, *inputs):",
        "    env = self._new_env(inputs)",
    ]
    for index in range(op_count):
        lines.append(f"    self._run_op({index}, env)")
    lines.append("    return self._materialize_output(env)")
    return "\n".join(lines) + "\n"
